version: 2

jobs:
  build:
    working_directory: ~/con-tools-model
    docker:
      - image: circleci/openjdk:11-jdk-node-browsers
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - restore_cache:
          key: con-tools-model-{{ checksum "pom.xml" }}
      - run:
          name: configure test containers
          command: |
            echo 'ryuk.container.timeout = 120' >> .testcontainers.properties
            echo 'checks.disable = true' >> .testcontainers.properties
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: con-tools-model-{{ checksum "pom.xml" }}
      - run:
          name: Update docker config
          command: |
            mkdir -p $HOME/.docker
            echo '{"auths":{}}' > $HOME/.docker/config.json
      - run:
          name: Build and Deploy
          command: mvn deploy -X
      - store_artifacts:
          path: target/model-*.jar
